[package]
name = "geograf"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "geograf_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "migrate", "json"] }
anyhow = "1.0.100"
ts-rs = { version = "11.1.0", features = ["serde-json-impl"] }
tauri-plugin-dialog = "2"
reqwest = { version = "0.12.24", features = ["stream"] }
encoding_rs = "0.8.35"
strum = { version = "0.27.2", features = ["derive"] }
itertools = "0.14.0"
tokio = { version = "1.48.0", features = ["macros", "tokio-macros"] }
uuid = { version = "1.18.1", features = ["v4"] }
async-trait = "0.1.89"
polars = { version = "0.52.0", features = ["serde", "serde-lazy", "json", "lazy", "csv", "dtype-full", "temporal", "parquet", "dtype-datetime", "timezones", "strings", "mode", "round_series", "abs"] }
pest = "2.8.3"
pest_derive = "2.8.3"
thiserror = "2.0.17"
lazy_static = "1.5.0"
futures = "0.3.31"
chrono = "0.4.42"
futures-util = "0.3.31"

[dev-dependencies]
rstest = "0.26.1"
tempfile = "3.23.0"

