// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ChartNodeData = { label: string, chart_type: string, x_axis: string, y_axis: Array<string>, limit: number | null, options: JsonValue | null, };
