// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DemoCategory } from "./DemoCategory";

export type Demo = { name: string, description: string, category: DemoCategory, flow: string, };
