// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExpressionError = { "ParseError": { msg: string, span: [number, number], } } | { "IllegalArgument": string } | { "Unsupported": { name: string, span: [number, number], rule: string | null, } };
