// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { Node } from "./Node";

export type Flow = { id: string, name: string, nodes: Array<Node>, edges: Array<Edge>, created_at: string, updated_at: string, };
