// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupByNodeData = { label: string, exprs: Array<string>, aggrs: Array<string>, sort: string | null, };
