// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JoinNodeData = { label: string, how: string, on: string | null, left_on: string | null, right_on: string | null, };
