// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeReaderOptions = { output: string, page: number, page_size: number, select: Array<string> | null, append: boolean, filter: string | null, sort: Array<[string, boolean]> | null, };
