// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodePosition } from "./NodePosition";
import type { NodeType } from "./NodeType";

export type Node = { id: string, data: any, type: NodeType | null, position: NodePosition, };
