// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeReaderOptions } from "./NodeReaderOptions";

export type NodeReadOutput = { data: any, total: number, columns: {name: string, dtype: string}[] | null, options: NodeReaderOptions, };
