// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeExecutorOptions = { run_id: string, page: number, page_size: number, diagnostic: boolean, };
