// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeType = "SourceNode" | "SinkNode" | "SelectNode" | "FilterNode" | "GroupByNode" | "JoinNode" | "SortNode" | "ChartNode" | "ConcatNode" | "DescribeNode" | "Unknown";
