// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeReadOutput } from "./NodeReadOutput";

export type NodeExecutionPreview = { output: NodeReadOutput | null, errors: Array<string>, };
