// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SelectNodeData = { label: string, exprs: Array<string>, with_columns: boolean, };
