// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataFormat } from "./DataFormat";
import type { JsonValue } from "./serde_json/JsonValue";

export type SinkNodeData = { label: string, dest: string, format: DataFormat, limit: number | null, options: JsonValue | null, };
