// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataFormat } from "./DataFormat";

export type SourceNodeData = { label: string, source: string, format: DataFormat, headers: Array<[string, string]> | null, cache: boolean, };
